// list
export const EVENTLIST_REQUESTED = 'EVENTLIST_REQUESTED';
export const EVENTLIST_SUCCESS = 'EVENTLIST_SUCCESS';
export const EVENTLIST_FAILED = 'EVENTLIST_FAILED';

//Create Event
export const CREATE_EVENT_REQUESTED = 'CREATE_EVENT_REQUESTED';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILED = 'CREATE_EVENT_FAILED';

